### ISSUE TITLE
bash segfaults when runs inside virtual chroot

### ISSUE THREAD

**Issue by rd235** [virtualsquare/vuos#15]
test case:
$ vu_insmod mountreal
$ busybox mount -t mountreal / /mnt
$ /usr/sbin/chroot /mnt

(in the same scenario "/usr/sbin/chroot /mnt busybox sh" or "/usr/sbin/chroot /mnt" work properly.

**Comment by wikilele** [comment]
I've tried, unsuccessfully, to find and remove this bug. I'll write here what I found.

The main problem seems to occur immediately after the conclusion of a binary file task.

For example, looking at the file **/etc/bash.bashrc**, if */etc/debian_chroot* exists in the system, the bash segfaults after the completion of `cat /etc/debian_chroot`.
So the `cat` command is executed succesfully, but (more or less) when the control goes back to
 **/etc/bash.bash** it segfaults.

Other examples could be the `/bin/sh lesspipe` in **~/.bashrc**
or `basename $0` in **/bin/lesspipe** :
in both of this cases the statement (*/bin/sh*, *basename*) is completed but then the segfaults occurs.

**Comment by wikilele** [comment]
There is also another problem related to  `/bin/sh lesspipe` in **~/.bashrc**:
when it is executed gives this error 
**/bin/dash: 0: Can't open /mnt/bin/lesspipe**
because when the module `open` is called, the path given to it is  _/mnt/mnt/bin/lesspipe_
so the module just takes off one _/mnt_ and do a `open(/mnt/bin/lesspipe,...)`.

This error occurs because of the `if (vu_fs_is_chroot()) rewrite_syspath(sd, sd->extra->path); `
statement in **vu_execute.c** .
This statement stores in `sd->syscall_args[0]` the path   _/mnt/bin/lesspipe_ (obtained by the canonicalization). Then, when the` execve` syscall is managed, 
`argv_addhead(argv_list, sd->syscall_args[0], NULL); `in **vu_wrap_execve.c** changes, in the process memory, _/bin/lesspipe_ to  _/mnt/bin/lesspipe_.

Finally, when the process does `open(/mnt/bin/lesspipe,...)`, this path is canonicalized again
returning  _/mnt/mnt/bin/lesspipe_ that is used by the module producing the error.

Deleting the `if `statement in **vu_execute.c** solve this problem, but it probably isn't the best solution.

If that line is deleted `/bin/sh lesspipe `is executed on the right file, but the problem with 
`basename $0` in **/bin/lesspipe** still remains.

**Comment by rd235** [comment]
Fixed.
